BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS "Subjects" (
	`ID` 	INTEGER PRIMARY KEY AUTOINCREMENT,
	`Code`  TEXT,
	`Name` 	TEXT
);

CREATE TABLE IF NOT EXISTS "Courses" (
	`ID`  INTEGER PRIMARY KEY AUTOINCREMENT,
	`CRN`  INTEGER,
	`CourseNumber` 	INTEGER,
	`RoomID` INTEGER,
	`Section` TEXT,
	`Name` TEXT,
	`StartTime` TEXT,
	`EndTime` TEXT,
	`Days` TEXT,
	`StartDate` Date,
	`EndDate` Date,
	FOREIGN KEY(RoomID) REFERENCES Rooms(ID)
);

CREATE TABLE IF NOT EXISTS "Buildings" (
	`ID` INTEGER PRIMARY KEY AUTOINCREMENT,
	`Name` 	TEXT
);

CREATE TABLE IF NOT EXISTS "ClassRooms" (
	`ID` 	INTEGER PRIMARY KEY AUTOINCREMENT,
	'BuildingID' INTEGER,
	`Number`	INTEGER,
	FOREIGN KEY(BuildingID) REFERENCES Buildings(ID),
	FOREIGN KEY(Number) REFERENCES Courses(Room)
);

CREATE TABLE IF NOT EXISTS "Rooms" (
	`ID` 	INTEGER PRIMARY KEY AUTOINCREMENT,
	'BuildingID' INTEGER,
	`Number`	INTEGER,
	FOREIGN KEY(BuildingID) REFERENCES Buildings(ID)
);

END TRANSACTION;